services:
  enterpriseapi:
    image: ${DOCKER_REGISTRY-}enterpriseapi
    container_name: "enterpriseapi"
    build:
      context: ./EnterpriseApi
      dockerfile: EnterpriseApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - "enterprisedb"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    networks:
      - productnetwork
    volumes:
      - ${HOME}/.dotnet:/root/.dotnet  # Bind mount to copy .dotnet folder (including certificates)
    restart: 
      on-failure

  enterprisedb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "enterprisesql"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Enterprise123456.
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - productnetwork

  enterpriseredis:
    image: "redis/redis-stack:latest"
    container_name: "enterpriseredis"
    ports:
      - "6379:6379"
    networks:
      - productnetwork

networks:
  productnetwork:

volumes:
  sqlvolume:
